advisor:
  file-sink:
    enabled: true
    dir: /var/log/pg-advisor
    filename: "{queryId}.jsonl"
    include-plan: true
    compress: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
